apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: filebeat
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - name: filebeat
        image: filebeat:latest
        imagePullPolicy: Always
        env:
          - name: LOGSTASH_HOSTS
            value: "'isnotusedd:5000'"
          - name: LOG_LEVEL
            value: info
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/filebeat
        - name: certs
          mountPath: /var/lib/puppet/ssl/certs
        - name: keys
          mountPath: /var/lib/puppet/ssl/private_keys
        - name: blaha
          mountPath: /etc/pki/tls/certs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: certs
        hostPath:
          path: /var/lib/puppet/ssl/certs
      - name: keys
        hostPath:
          path: /var/lib/puppet/ssl/private_keys
      - name: blaha
        hostPath:
          path: /etc/pki/tls/certs
      - name: config-volume
        configMap:
          name: filebeat-config
         
