apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: web-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: web_app:1.0
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: secret
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/
          name: config
      volumes:
       - name: data
         emptyDir: {}
       - name: config
         configMap:
           name: nginx-conf
           items: 
           - key: nginx.conf
             path: nginx.conf
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-app
spec:
  rules:
  - http:
      paths:
      - path: /web-app
        backend:
          serviceName: web-app
          servicePort: http
