apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote-app
  labels:
    app: redis
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: vote-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis  # or just image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote-app
  labels:
    app: postgres
spec:
  ports:
    # the port that this service should serve on
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: vote-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db
        image: postgres:9.4
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote-app
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    nodePort: 30400
  selector:
    app: vote
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
  namespace: vote-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: vote_app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: vote-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker_app:1.0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote-app
  labels:
    app: result
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
   - port: 80
     nodePort: 30200
  selector:
    app: result
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: vote-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: result_app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
