apiVersion: v1
kind: Service
metadata:
  name: curl
  labels: 
    app: curl
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: curl
---
apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - image: webwurst/curl-utils
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curl
  restartPolicy: Always
