apiVersion: v1
kind: Service
metadata:
  labels:
    name: kubernetes-cockpit
  name: kubernetes-cockpit
  namespace: default
spec:
  ports:
    nodePort: 30900
    port: 443
    protocol: TCP
    targetPort: 9090
  selector:
    name: kubernetes-cockpit
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: kubernetes-cockpit
  name: kubernetes-cockpit
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kubernetes-cockpit
    spec:
      containers:
      - env:
        - name: KUBE_INSECURE
          value: "true"
        image: cockpit/kubernetes:latest
        imagePullPolicy: Always
        name: kubernetes-cockpit
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
