apiVersion: v1
kind: Service
metadata:
  name: jmxtest
  labels:
    app: jmxtest
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: jmxtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmxtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jmxtest
    spec:
      containers:
      - name: jmxtest
        image: jmxtest:latest
        ports:
        - containerPort: 8080
