apiVersion: v1
kind: Service
metadata:
  name: probe-app
  labels:
    app: probe-app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30139
    protocol: TCP
    name: http
  selector:
    app: probe-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: probe-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: probe-app
    spec:
      containers:
      - name: probe-app
        image: probe-app:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: webwurst/curl-utils
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            host: probe-app.default
        command: ['/bin/sh', '-c']
        args: ['while true; do curl -s $PROBE_APP_SERVICE_HOST:$PROBE_APP_SERVICE_PORT; echo " "; done']
